const users = [
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    name: "Kevin",
    email: "kevin@rhythmcodestudio.tech",
    password: "password",
  },
];

const pages = [
  {
    id: "1",
    name: "Home",
    slug: "home",
    url: "/",
    page_title: "The Long Emergency",
    sections: [],
  },
  {
    id: "2",
    name: "About",
    slug: "about",
    url: "/about",
    page_title: "About",
    sections: [],
  },
  {
    id: "3",
    name: "Music",
    slug: "music",
    url: "/music",
    page_title: "Music",
    sections: [],
  },
  {
    id: "4",
    name: "Shows",
    slug: "shows",
    url: "/shows",
    page_title: "Shows",
    sections: [],
  },
  {
    id: "5",
    name: "Blog",
    slug: "blog",
    url: "/blog",
    page_title: "Blog",
    sections: [],
  },
  {
    id: "6",
    name: "Contact",
    slug: "contact",
    url: "/contact",
    page_title: "Contact",
    sections: [],
  },
  {
    id: "7",
    name: "Merch",
    slug: "merch",
    url: "/merch",
    page_title: "Merch",
    sections: [],
  },
  {
    id: "8",
    name: "Login",
    slug: "login",
    url: "/login",
    page_title: "Login",
    sections: [],
  },
  {
    id: "9",
    name: "Admin",
    slug: "admin",
    url: "/admin",
    page_title: "Admin",
    sections: [],
  },
];

const songs = [
  {
    id: 1,
    title: "I-35",
    artist: "The Long Emergency",
    album: 1,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 1,
    src: "/music/i-35/mp3/i-35.mp3",
    bandcamp_url: "https://thelongemergency.bandcamp.com/track/i-35",
    lyrics: ["", ""],
  },
  {
    id: 2,
    title: "Sing Me To Sleep",
    artist: "The Long Emergency",
    album: 1,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 2,
    src: "/music/i-35/mp3/sing-me-to-sleep.mp3",
    bandcamp_url:
      "https://thelongemergency.bandcamp.com/track/sing-me-to-sleep",
    lyrics: ["", ""],
  },
  {
    id: 3,
    title: "Last Night",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 1,
    src: "/music/starting-over/mp3/last-night.mp3",
    bandcamp_url: "https://thelongemergency.bandcamp.com/track/last-night",
    lyrics: 
      [
        "Well I've got this little life and I've got a little bit of gasoline. I just need a little spark to light a big fire for all to see. So I've got one question. Have you got a match for me?Let's light up the night and burn this motherfucker clean.",
        "Tonight. Tonight. Tonight I'm gonna make everything right.",
        "When I left your house this morning I felt more than a bit sad but more so I felt thankful for what we do still have. Last night I openend that old familiar door. The one I've closed so many times. Such solemn promisies I swore.",
        "Last night last night last night I just couldn't sleep tight.",
        "When I woke from sleep that morning I humbled myself and prayed. And yet still I felt the summons. Demons or I'm insane. Last night I opened that old familiar door. The one I've closed so many times. Such solemn promisies I swore.",
        "Last night last night last night I just couldn't sleep tight.",
        "When I woke from sleep this morning I humbled myself and prayed. And yet still I feel the summons. Demons or I'm insane. Tonight I'll knock upon that old familiar door. The one I closed just last night. Such solemn promisies I swore.",
        "Last night last night last night I just couldn't sleep tight.",
        "Sleep tight. Sleep tight. Sleep tight. This might be your last night.",
        "I just want to sleep."
      ]
  },
  {
    id: 4,
    title: "Snow Emergency",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 2,
    src: "/music/starting-over/mp3/snow-emergency.mp3",
    bandcamp_url: "https://thelongemergency.bandcamp.com/track/snow-emergency",
    lyrics: [
      "Do you think you could give me a push? My beat up pickup truck don't go in reverse. It sucks being stuck in the snow but it's worse when your pickup truck don't go in reverse. In the morning the plows and tow trucks will come round",
      "Why do I live in this town year round?",
      "Do you think you could give me a push? Just a little jump start and I think I should be good. In the morning the plows and tow trucks will come round.",
      "Why do I live in this town year round? This time of year the snow swallows all the sound. This time of year the sun barely comes around. This time of year I want to sleep beneath the ground.",
      "Do you think you could give me a push? Right off of this ledge? I know you've had the urge and sometimes I swear I wish you would. In the morning the cops and tow trucks will come round",
      "Why do I live in this town year round? This time of year the snow swallows all the sound. This time of year the sun barely comes around. This time of year I want to sleep beneath the ground.",
      "Why do I live in this town year round? This time of year the snow swallows all the sound. This time of year the sun barely comes around. This time of year I want to sleep beneath the ground. This time of year I want to sleep beneath the ground. This time of year I want to sleep beneath the ground.",
      "This time of year I want to sleep. Just close my eyes and dream. I sure could use some peace. I'll see you in the spring."
    ]
  },
  {
    id: 5,
    title: "I-35",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 3,
    src: "/music/starting-over/mp3/i-35.mp3",
    bandcamp_url: "https://thelongemergency.bandcamp.com/track/i-35-2",
    lyrics: ["", ""],
  },
  {
    id: 6,
    title: "I Am Not Sorry",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 4,
    src: "/music/starting-over/mp3/i-am-not-sorry.mp3",
    bandcamp_url: "https://thelongemergency.bandcamp.com/track/i-am-not-sorry",
    lyrics: ["", ""],
  },
  {
    id: 7,
    title: "Twist The Knife",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 5,
    src: "/music/starting-over/mp3/twist-the-knife.mp3",
    bandcamp_url: "https://thelongemergency.bandcamp.com/track/twist-the-knife",
    lyrics: ["", ""],
  },
  {
    id: 8,
    title: "Starting Over",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 6,
    src: "/music/starting-over/mp3/starting-over.mp3",
    bandcamp_url: "https://thelongemergency.bandcamp.com/track/starting-over",
    lyrics: ["", ""],
  },
  {
    id: 9,
    title: "Sing Me To Sleep",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 7,
    src: "/music/starting-over/mp3/sing-me-to-sleep.mp3",
    bandcamp_url:
      "https://thelongemergency.bandcamp.com/track/sing-me-to-sleep-2",
    lyrics: ["", ""],
  },
];

const albums = [
  // {
  //   id: 3,
  //   title: "Boxcutter",
  //   artist: "The Long Emergency",
  //   year: 2025,
  //   genre: "Rock",
  //   cover_image: "/music/starting-over/album-art/cover.jpg",
  //   type: "album",
  //   zip: "/music/starting-over/starting-over-full.zip"
  // },
  {
    id: 2,
    title: "Starting Over",
    artist: "The Long Emergency",
    year: 2013,
    genre: "Rock",
    cover_image: "/music/starting-over/album-art/cover.jpg",
    type: "album",
    zip: "/music/starting-over/starting-over-full.zip",
    bandcamp_url: "https://thelongemergency.bandcamp.com/album/starting-over",
  },
  {
    id: 1,
    title: "I-35",
    artist: "The Long Emergency",
    year: 2013,
    genre: "Rock",
    cover_image: "/music/i-35/album-art/i-35-cover.jpg",
    type: "single",
    zip: "/music/i-35/i-35-full.zip",
    bandcamp_url: "https://thelongemergency.bandcamp.com/album/i-35",
  },
];

const merch = [
  {
    id: 1,
    name: "Starting Over - CD",
    price: 10,
    image: "/images/starting-over.jpg",
    description:
      "The debut album from The Long Emergency on CD. Includes digital download (MP3).",
    stripe_url: "https://buy.stripe.com/test_14k9CVeHc33c1i0bIK",
  },
  {
    id: 2,
    name: "Starting Over - MP3",
    price: 5,
    image: "/images/starting-over.jpg",
    description:
      "Digital copy of the debut album from The Long Emergency. Includes album art.",
    stripe_url: "https://buy.stripe.com/test_fZe8yRgPk6fof8QbIJ",
  },
  {
    id: 3,
    name: "I-35 - MP3",
    price: 2,
    image: "/images/i-35.jpg",
    description:
      "Digital copy of the single I-35 from The Long Emergency. Includes the B-side Sing Me To Sleep.",
    stripe_url: "https://buy.stripe.com/test_9AQ3ex9mSavEf8Q8wz",
  },
];

module.exports = {
  users,
  pages,
  albums,
  songs,
  merch,
};
