const users = [
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    name: "Kevin",
    email: "kevin@rhythmcodestudio.tech",
    password: "password",
  },
];

const pages = [
  {
    id: "1",
    name: "Home",
    slug: "home",
    url: "/",
    page_title: "The Long Emergency",
    sections: [],
  },
  {
    id: "2",
    name: "About",
    slug: "about",
    url: "/about",
    page_title: "About",
    sections: [],
  },
  {
    id: "3",
    name: "Music",
    slug: "music",
    url: "/music",
    page_title: "Music",
    sections: [],
  },
  {
    id: "4",
    name: "Shows",
    slug: "shows",
    url: "/shows",
    page_title: "Shows",
    sections: [],
  },
  {
    id: "5",
    name: "Blog",
    slug: "blog",
    url: "/blog",
    page_title: "Blog",
    sections: [],
  },
  {
    id: "6",
    name: "Contact",
    slug: "contact",
    url: "/contact",
    page_title: "Contact Page",
    sections: [],
  },
  {
    id: "7",
    name: "Merch",
    slug: "merch",
    url: "/merch",
    page_title: "Merch",
    sections: [],
  },
  {
    id: "8",
    name: "Login",
    slug: "login",
    url: "/login",
    page_title: "Login",
    sections: [],
  },
  {
    id: "9",
    name: "Admin",
    slug: "admin",
    url: "/admin",
    page_title: "Admin",
    sections: [],
  },
];

const songs = [
  {
    id: 1,
    title: "I-35",
    artist: "The Long Emergency",
    album: 1,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 1,
    src: "/music/i-35/mp3/i-35.mp3",
  },
  {
    id: 2,
    title: "Sing Me To Sleep",
    artist: "The Long Emergency",
    album: 1,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 2,
    src: "/music/i-35/mp3/sing-me-to-sleep.mp3",
  },
  {
    id: 3,
    title: "Last Night",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 1,
    src: "/music/starting-over/mp3/last-night.mp3",
  },
  {
    id: 4,
    title: "Snow Emergency",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 2,
    src: "/music/starting-over/mp3/snow-emergency.mp3",
  },
  {
    id: 5,
    title: "I-35",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 3,
    src: "/music/starting-over/mp3/i-35.mp3",
  },
  {
    id: 6,
    title: "I Am Not Sorry",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 4,
    src: "/music/starting-over/mp3/i-am-not-sorry.mp3",
  },
  {
    id: 7,
    title: "Twist The Knife",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 5,
    src: "/music/starting-over/mp3/twist-the-knife.mp3",
  },
  {
    id: 8,
    title: "Starting Over",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 6,
    src: "/music/starting-over/mp3/starting-over.mp3",
  },
  {
    id: 9,
    title: "Sing Me To Sleep",
    artist: "The Long Emergency",
    album: 2,
    year: 2013,
    genre: ["Rock", "Indie"],
    track_number: 7,
    src: "/music/starting-over/mp3/sing-me-to-sleep.mp3",
  },
];

const albums = [
  {
    id: 1,
    title: "I-35",
    artist: "The Long Emergency",
    year: 2013,
    genre: "Rock",
    cover_image: "/recordings/i-35/album-art/i-35-cover.jpg",
    type: "single",
   
  },
  {
    id: 2,
    title: "Starting Over",
    artist: "The Long Emergency",
    year: 2013,
    genre: "Rock",
    cover_image: "/recordings/starting-over/album-art/cover.jpg",
    type: "album",
    
  },
];

module.exports = {
  users,
  pages,
  albums,
  songs,
};
